INSERT INTO lw.Orders (
    pkOrderId,  
    cFullName,
    cEmailAddress,
    cPostcode,
    dReceivedDate,
    dProcessedOn,
    fPostageCost,
    fTotalCharge,
    cCurrency,
    nOrderId,
    bReplace,
    Source,
    bProcessed,
    fTax,
    fkCountryId,
    fkPostalServiceId,
    fkPackagingGroupId,
    ReferenceNum,
    ExternalReference,
    PostalTrackingNumber,
    CreateOnly,
    CreatedDate,
    Address1,
    Address2,
    Address3,
    Town,
    Region,
    LifeStatus,
    BuyersPhoneNumber,
    Company,
    SubSource,
    AddressVerified,
    Subtotal,
    PostageCostExTax,
    CountryTaxRate,
    RecalculateTaxRequired,
    ChannelBuyerName,
    HoldOrCancel,
    Weight,
    TotalDiscount,
    fkBankId,
    FulfillmentLocationId,
    SecondaryReferenceNum,
    PostalServiceCost,
    FulfillmentCenterAcknowledge,
    PostageDiscount,
    ConversionRate
)
SELECT
    TRY_CAST(pkOrderID AS uniqueidentifier),
    cFullName,
    cEmailAddress,
    REPLACE(cPostCode, CHAR(9), '') AS cPostcode,
    TRY_CAST(dReceivedDate AS DATETIME),
    TRY_CAST(dProcessedOn AS DATETIME),
    fPostageCost,
    fTotalCharge,
    cCurrency,
    nOrderId,
    NULL AS bReplace,
    Source,
    NULL AS bProcessed,
    fTax,
    NULL AS fkCountryId,
    NULL AS fkPostalServiceId,
    NULL AS fkPackagingGroupId,
    ReferenceNum,
    ExternalReference,
    PostalTrackingNumber,
    NULL AS CreateOnly,
    NULL AS CreatedDate,
    Address1,
    Address2,
    Address3,
    Town,
    Region,
    NULL AS LifeStatus,
    NULL AS BuyersPhoneNumber,
    Company,
    SubSource,
    NULL AS AddressVerified,
    Subtotal,
    PostageCostExTax,
    CountryTaxRate,
    NULL AS RecalculateTaxRequired,
    ChannelBuyerName,
    HoldOrCancel,
    NULL AS Weight,
    TotalDiscount,
    NULL AS fkBankId,
    NULL AS FulfillmentLocationId,
    NULL AS SecondaryReferenceNum,
    NULL AS PostalServiceCost,
    NULL AS FulfillmentCenterAcknowledge,
    NULL AS PostageDiscount,
    NULL AS ConversionRate
FROM 
    [linnworks].[staging].[_airbyte_raw_processed_orders] AS data
WHERE 
    pkOrderID IS NOT NULL
    AND NOT EXISTS (
        SELECT 1 
        FROM lw.Orders o 
        WHERE o.pkOrderId = TRY_CAST(data.pkOrderID AS uniqueidentifier)
    );
